version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    mem_limit: 250000000
    #container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    #container_name: whoami
    mem_limit: 250000000
    environment:
      - VIRTUAL_HOST=ecs2.dansullivan.io
