name: Github Actions
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  schedule:
  - cron: "0 0 * * *"
jobs:
  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Build containers
      run: ./build.sh
